# Final expense state-page copy. Every figure is from the verified 2026
# price-list analysis in docs/content/state-pages.md (state medians; national
# medians $1,995 cremation / $2,800 immediate burial / $2,195 basic services
# fee / $6,415 full traditional funeral; cemetery $2,000-$5,000). Regulator
# details are from each department's homepage, fetched 12 Sep 2026.
P = lambda *ps: "\n".join(f"<p>{p}</p>" for p in ps)
COPY = {}
# Recommended coverage band per state, rendered in the coverage callout. Every coverage note below
# concludes at the same two figures: cremation with a gathering within $10,000, burial with a
# service toward $15,000. Override per slug if a state's note ever concludes differently.
BAND = {slug: (10000, 15000) for slug in ("colorado", "tennessee", "florida", "texas", "california", "pennsylvania", "ohio", "michigan", "north-carolina", "georgia", "arizona")}

COPY["colorado"] = dict(
 intro=P("A direct cremation in Colorado has a median cost of $1,650 and an immediate burial $2,565 &mdash; 17% and 8% below the national medians, and cheaper than average on every funeral-home charge we measured. Final expense insurance covers those costs with a small whole life policy, usually $5,000 to $25,000, that pays cash directly to your family.",
         "This is our home state. Senior Solutions Insurance works from Greenwood Village, and the licensed agent who calls you back sits in that office."),
 obs="<p><strong>Colorado is cheaper than average on every measure.</strong> Cremation at $1,650 is 17% below the national median and burial at $2,565 is 8% below; the non-declinable basic services fee, $1,985, is 10% below. Colorado families generally need less coverage for the funeral home&rsquo;s bill than the national averages suggest &mdash; the cemetery is where the number climbs.</p>",
 cov="<p>For a Colorado family choosing burial, the funeral home&rsquo;s bill is below average but the cemetery&rsquo;s is not, so the Front Range plot price tends to decide the total. Ten thousand dollars covers the simplest burial with room to spare; a full service with a viewing points toward $10,000 to $15,000.</p>",
 reg="<p>Final expense policies sold in Colorado are regulated by the <a href=\"https://doi.colorado.gov/\" rel=\"noopener\">Colorado Division of Insurance</a>, which licenses the agents and carriers, takes complaints, and offers a &ldquo;Find Lost Life Insurance&rdquo; search on its homepage for families who believe a deceased relative had a policy they cannot locate &mdash; worth knowing before you buy, and worth telling your family about after. Senior Solutions Insurance is licensed there, in our own state; you can verify our agents on the same site.</p>",
 faq=[
  ("How much does a funeral cost in Colorado?", "The 2026 median from 31 Colorado funeral home price lists is $1,650 for a direct cremation and $2,565 for an immediate burial, both below the national medians of $1,995 and $2,800. Those are funeral-home charges only; the cemetery bills a plot, vault, opening and closing, and headstone separately, typically $2,000&ndash;$5,000 or more."),
  ("Is final expense insurance cheaper in Colorado?", "No. Premiums are set by your age, gender, tobacco use and health, and a 65-year-old in Denver is quoted from the same tables as a 65-year-old in Atlanta. What differs in Colorado is what you are insuring against: funeral-home charges here run 8 to 17% below national, so the same $10,000 policy stretches further."),
  ("How much coverage do I need for a Colorado funeral?", "Add the cemetery to the funeral home. An immediate burial at Colorado&rsquo;s $2,565 median plus $2,000&ndash;$5,000 of cemetery costs is $4,565&ndash;$7,565; a full traditional funeral with a viewing lands at $8,415&ndash;$11,415. Most Colorado families land between $10,000 and $15,000 once medical bills and small debts are added."),
  ("What if my family cannot find the policy after I die?", "Colorado is one of the states whose insurance regulator runs a lost-policy search: the Colorado Division of Insurance&rsquo;s &ldquo;Find Lost Life Insurance&rdquo; service, on its homepage, asks participating insurers to check their records for a deceased person. It is a backstop, not a plan &mdash; tell the person you name as beneficiary where the policy is and who the agent was."),
  ("Where is Senior Solutions Insurance located?", "In Greenwood Village, Colorado, at 5775 DTC Blvd, Suite 250-S. The agent who calls you back works from that office and is licensed by the Colorado Division of Insurance, where you can verify the license."),
 ],
)

COPY["tennessee"] = dict(
 intro=P("A direct cremation in Tennessee has a median cost of $2,348 &mdash; 18% above the national median of $1,995 &mdash; and an immediate burial $2,990, which is also above the national figure. Final expense insurance covers those costs with a small whole life policy, usually $5,000 to $25,000, that pays cash directly to your family."),
 obs="<p><strong>Tennessee runs above the national median on every funeral-home charge.</strong> Cremation at $2,348 is 18% above national, burial at $2,990 is 7% above, and the non-declinable basic services fee of $2,298 is 5% above. If you assumed a Tennessee funeral would be cheaper than average, the price lists say otherwise; plan the coverage amount accordingly.</p>",
 cov="<p>Because Tennessee&rsquo;s funeral-home charges sit above national, a Tennessee family should not round down. An immediate burial with cemetery costs already approaches $8,000 at the top of the range; a full service with a viewing points toward $15,000 rather than $10,000.</p>",
 reg="<p>Final expense policies sold in Tennessee are regulated by the Insurance Division of the <a href=\"https://www.tn.gov/commerce/insurance-division.html\" rel=\"noopener\">Tennessee Department of Commerce and Insurance</a>, whose site lets you verify an agent&rsquo;s license and file a complaint. Ask your agent for their Tennessee license number and check it before you apply.</p>",
 faq=[
  ("How much does a funeral cost in Tennessee?", "From 26 Tennessee funeral home price lists collected in 2026, the median is $2,348 for a direct cremation and $2,990 for an immediate burial. Both are above the national medians of $1,995 and $2,800. Cemetery costs &mdash; plot, vault, opening and closing, headstone &mdash; are billed separately and add $2,000&ndash;$5,000 or more."),
  ("Why is cremation more expensive in Tennessee than the national average?", "The price lists do not say why, only that it is: Tennessee&rsquo;s $2,348 median for direct cremation is 18% above the national $1,995, and the basic services fee of $2,298 is above national too. The practical point is not to size a Tennessee policy on the national average."),
  ("How much final expense coverage does a Tennessee family need?", "An immediate burial at Tennessee&rsquo;s $2,990 median plus $2,000&ndash;$5,000 of cemetery costs is $4,990&ndash;$7,990 before any service. A full traditional funeral with a viewing runs $8,415&ndash;$11,415 with the cemetery included. With medical bills and small debts added, $10,000 to $15,000 is where most Tennessee families land, and the higher figure is the safer one here."),
  ("Does Tennessee&rsquo;s higher funeral cost change my premium?", "No &mdash; it changes the amount you should buy. Premiums come from the same age, gender, tobacco and health tables everywhere, but Tennessee&rsquo;s $2,298 basic services fee and $2,990 burial median mean a $10,000 policy covers a smaller share of a Tennessee funeral than it would in Arizona or Colorado. Most Tennessee families who want a burial with a service should be looking at $15,000."),
  ("Who regulates final expense insurance in Tennessee?", "The Insurance Division of the Tennessee Department of Commerce and Insurance, which licenses the agents and carriers and whose website lets you verify a license and file a complaint. The same department houses the TennCare Oversight Division, so a Tennessee family sorting out a relative&rsquo;s Medicaid and a funeral policy at the same time is dealing with one agency. Ask your agent for their Tennessee license number."),
 ],
)

COPY["florida"] = dict(
 intro=P("A direct cremation in Florida has a median cost of $1,882 and an immediate burial $2,695 &mdash; within a few percent of the national medians on every funeral-home charge. What moves the total for a Florida family is not the funeral home; it is the cemetery, which is left out of every published average. Final expense insurance covers both with a small whole life policy, usually $5,000 to $25,000, that pays cash directly to your family."),
 obs="<p><strong>Florida tracks the national median closely</strong> &mdash; cremation 6% below, burial 4% below, the basic services fee 8% below &mdash; so the national averages are a fair guide to the funeral home&rsquo;s bill here. The figure they leave out is the cemetery: a plot, vault, opening and closing and a marker add $2,000&ndash;$5,000 or more, and that line, not the funeral home&rsquo;s, is what moves a Florida total.</p>",
 cov="<p>With the funeral home near the national average, Florida&rsquo;s coverage decision comes down to the cemetery and to whether the family wants a viewing. Cremation with a memorial gathering can be covered comfortably by $10,000; burial with a service in a metro-area cemetery points toward $15,000.</p>",
 reg="<p>Final expense policies sold in Florida are regulated through the Florida Department of Financial Services, whose <a href=\"https://www.myfloridacfo.com/division/consumers\" rel=\"noopener\">Division of Consumer Services</a> runs the consumer helpline and takes complaints about agents and insurers. Unusually, the same department also regulates Florida&rsquo;s funeral homes and cemeteries through its Division of Funeral, Cemetery and Consumer Services &mdash; so the agency that licenses your insurance agent is also the one that oversees the funeral home&rsquo;s price list.</p>",
 faq=[
  ("How much does a funeral cost in Florida?", "From 32 Florida funeral home price lists collected in 2026, the median direct cremation is $1,882 and the median immediate burial $2,695 &mdash; within a few percent of the national medians of $1,995 and $2,800. Those are funeral-home charges only; cemetery costs add $2,000&ndash;$5,000 or more on top."),
  ("Why do Florida funeral costs vary so much between quotes?", "Because the cemetery is a separate business with a separate bill. Florida&rsquo;s funeral-home medians are steady and close to national &mdash; $1,882 for cremation against $1,995, $2,695 for burial against $2,800 &mdash; so the spread you see between Florida quotes is mostly the cemetery, the casket and whether a viewing is included. The Florida Department of Financial Services regulates both the funeral homes and the cemeteries, and the FTC Funeral Rule entitles you to an itemized price list from any of them."),
  ("How much final expense coverage does a Florida family need?", "An immediate burial at Florida&rsquo;s $2,695 median plus $2,000&ndash;$5,000 of cemetery costs is $4,695&ndash;$7,695. A full traditional funeral with a viewing and cemetery costs lands at $8,415&ndash;$11,415. Add medical bills and small debts and most Florida families choose between $10,000 and $15,000."),
  ("Who do I complain to about a Florida funeral home or an insurance agent?", "The same department, as it happens. The Florida Department of Financial Services licenses insurance agents through its Division of Consumer Services and regulates funeral homes and cemeteries through its Division of Funeral, Cemetery and Consumer Services. Its consumer helpline handles both; the FTC Funeral Rule also gives you the right to an itemized price list from any Florida funeral home."),
  ("Can I buy final expense insurance in Florida if I spend part of the year elsewhere?", "Yes. A final expense policy is not tied to a funeral home or a state; it pays cash to the person you name, wherever the funeral takes place. If that ends up being Florida, the Florida medians &mdash; $1,882 for cremation, $2,695 for burial, plus the cemetery &mdash; are the right benchmark for the amount; if it happens in your other state, that state&rsquo;s figures apply and the cash benefit is the same. Tell the agent which state is your legal residence, because a Florida-issued policy falls under the Florida Department of Financial Services&rsquo; rules."),
 ],
)

COPY["texas"] = dict(
 intro=P("A direct cremation in Texas has a median cost of $2,015, right at the national median of $1,995, while an immediate burial at $2,890 sits above the national $2,800. Final expense insurance covers those costs with a small whole life policy, usually $5,000 to $25,000, that pays cash directly to your family."),
 obs="<p><strong>Texas splits the difference:</strong> cremation is 1% above national, essentially at it, while burial is 3% above and the non-declinable basic services fee of $2,245 is 2% above. In a state this size the medians hide a wide spread between the big metros and the rest, and the 40 price lists behind these figures make Texas one of the better-sampled states in the set.</p>",
 cov="<p>Texas burial costs run a little above national, and a metro cemetery in Dallas&ndash;Fort Worth, Houston or Austin is more likely to sit toward the top of the $2,000&ndash;$5,000 range than a rural one. A Texas family planning a burial with a service should size toward $15,000; cremation with a memorial is comfortably within $10,000.</p>",
 reg="<p>Final expense policies sold in Texas are regulated by the <a href=\"https://www.tdi.texas.gov/\" rel=\"noopener\">Texas Department of Insurance</a>, whose homepage lets you look up a company or agent and file a complaint. Texas also has a separate Office of Public Insurance Counsel that represents consumers in insurance matters, linked from the department&rsquo;s site. Ask your agent for their Texas license number.</p>",
 faq=[
  ("How much does a funeral cost in Texas?", "From 40 Texas funeral home price lists collected in 2026, the median direct cremation is $2,015 and the median immediate burial $2,890. Cremation is at the national median of $1,995; burial is above the national $2,800. Cemetery costs are separate and add $2,000&ndash;$5,000 or more."),
  ("Is burial or cremation the bigger saving in Texas?", "Cremation. The gap between Texas&rsquo;s $2,015 cremation and $2,890 burial medians is about 43% before the cemetery is counted, and choosing cremation also removes the plot, vault and marker. For a Texas family the choice between the two changes the coverage need by several thousand dollars."),
  ("How much final expense coverage does a Texas family need?", "An immediate burial at Texas&rsquo;s $2,890 median plus $2,000&ndash;$5,000 of cemetery costs is $4,890&ndash;$7,890. A full traditional funeral with a viewing and cemetery costs comes to $8,415&ndash;$11,415. With medical bills and small debts added, most Texas families land between $10,000 and $15,000."),
  ("Do Texas funeral costs differ between Houston and a small town?", "The medians above blend both, and the spread inside Texas is wide: 40 price lists across 254 counties is a large sample precisely because the state is. The basic services fee, $2,245 at the median, is the steadiest charge; the cemetery plot is where a Houston, Dallas or Austin funeral pulls away from a rural one. Ask the funeral home for its General Price List &mdash; Texas homes must provide it &mdash; and compare that fee first."),
  ("Who regulates final expense insurance in Texas?", "The Texas Department of Insurance licenses the agents and carriers; its homepage has an agent and company lookup and a complaint form. If a dispute goes further, Texas&rsquo;s Office of Public Insurance Counsel represents consumers in insurance matters."),
 ],
)

COPY["california"] = dict(
 intro=P("A direct cremation in California has a median cost of $1,895 and an immediate burial $2,499 &mdash; both below the national medians, and drawn from 90 funeral home price lists, the largest sample of any state in our data. Final expense insurance covers those costs with a small whole life policy, usually $5,000 to $25,000, that pays cash directly to your family."),
 obs="<p><strong>California&rsquo;s figures are the most reliable in the set</strong> &mdash; 90 price lists, three times the typical state &mdash; and they run below national on both measures: cremation 5% below and burial 11% below, with the basic services fee of $1,995 9% below. The funeral home is not where a California funeral gets expensive; the cemetery, which is a separate bill and is not in these medians, is where California costs vary most.</p>",
 cov="<p>California&rsquo;s funeral-home charges are below average; the cemetery is where the total moves, and in the coastal metros the upper end of the $2,000&ndash;$5,000 range is the realistic planning figure. A California family choosing burial should size toward $15,000; cremation is comfortably covered by $10,000.</p>",
 reg="<p>Final expense policies sold in California are regulated by the <a href=\"https://www.insurance.ca.gov/\" rel=\"noopener\">California Department of Insurance</a>, whose homepage has a &ldquo;Check License Status&rdquo; tool and complaint forms and which publishes a consumer complaint study comparing insurers. Ask your agent for their California license number and check it before you apply.</p>",
 faq=[
  ("How much does a funeral cost in California?", "From 90 California funeral home price lists collected in 2026 &mdash; the largest sample of any state &mdash; the median direct cremation is $1,895 and the median immediate burial $2,499, both below the national medians of $1,995 and $2,800. Cemetery costs are separate and, in California&rsquo;s coastal metros, often exceed the $2,000&ndash;$5,000 national range."),
  ("Why is a California funeral expensive if the funeral home is cheaper than average?", "Because the funeral home is only half the bill. California&rsquo;s funeral-home medians are 5 to 11% below national, but the cemetery &mdash; plot, vault, opening and closing, marker &mdash; is billed separately and is not in those medians, and it is the part of a California funeral that varies most from one cemetery to the next. Cremation, at a $1,895 median here, skips the plot entirely."),
  ("How much final expense coverage does a California family need?", "An immediate burial at California&rsquo;s $2,499 median plus $2,000&ndash;$5,000 of cemetery costs is $4,499&ndash;$7,499, and a full traditional funeral with a viewing and cemetery costs comes to $8,415&ndash;$11,415. In the coastal metros the cemetery can push those totals higher, so $15,000 is a reasonable target for burial; $10,000 covers cremation with a memorial."),
  ("How reliable are these California figures?", "More reliable than for any other state in our data: 90 price lists, against 13 for North Carolina and 24 for Pennsylvania. A median drawn from 90 funeral homes across a state of 58 counties is a genuine benchmark. The number it cannot include is your cemetery&rsquo;s plot price, which is where California varies most."),
  ("Who regulates final expense insurance in California?", "The California Department of Insurance, which licenses agents and carriers, has a &ldquo;Check License Status&rdquo; tool on its homepage, and publishes a consumer complaint study comparing insurers. Ask your agent for their California license number."),
 ],
)

COPY["pennsylvania"] = dict(
 intro=P("Pennsylvania has the highest basic services fee of the eleven states we cover: $2,562, 17% above the national median, and it is the one charge on a funeral bill that nobody can decline. Direct cremation, at $2,462, is 23% above national too. Final expense insurance covers those costs with a small whole life policy, usually $5,000 to $25,000, that pays cash directly to your family."),
 obs="<p><strong>Pennsylvania&rsquo;s non-declinable fee is the story.</strong> Under the FTC Funeral Rule, everything on a funeral home&rsquo;s price list is optional except the basic services fee, and in Pennsylvania that fee&rsquo;s median of $2,562 is the highest in our set and 17% above the national $2,195. Cremation at $2,462 is 23% above national; burial at $2,998 is 7% above. A Pennsylvania family cannot shop its way below that floor, so the coverage amount should assume it.</p>",
 cov="<p>Pennsylvania families should size toward the top of each band. The basic services fee alone is $2,562 before anything else is chosen, and burial with cemetery costs runs close to $8,000 at the upper end. A full service with a viewing points to $15,000; even cremation with a gathering is more comfortably covered by $10,000 here than in a below-average state.</p>",
 reg="<p>Final expense policies sold in Pennsylvania are regulated by the <a href=\"https://www.pa.gov/agencies/insurance\" rel=\"noopener\">Pennsylvania Insurance Department</a>, whose Consumer Help Center lets you ask a question or file a complaint and whose consumer services portal tracks the answer. Ask your agent for their Pennsylvania license number before you apply.</p>",
 faq=[
  ("How much does a funeral cost in Pennsylvania?", "From 24 Pennsylvania funeral home price lists collected in 2026, the median direct cremation is $2,462 and the median immediate burial $2,998, both above the national medians of $1,995 and $2,800. The basic services fee, $2,562, is the highest of the eleven states we cover. Cemetery costs add $2,000&ndash;$5,000 or more on top."),
  ("What is the basic services fee, and why does it matter in Pennsylvania?", "It is the one charge on a funeral bill you cannot decline: it covers the funeral director&rsquo;s time, planning, permits and coordination. Nationally the median is $2,195; in Pennsylvania it is $2,562, 17% higher. Every other line on the price list is a choice, so this fee sets the floor of any Pennsylvania funeral."),
  ("How much final expense coverage does a Pennsylvania family need?", "An immediate burial at Pennsylvania&rsquo;s $2,998 median plus $2,000&ndash;$5,000 of cemetery costs is $4,998&ndash;$7,998. A full traditional funeral with a viewing and cemetery costs comes to $8,415&ndash;$11,415, and Pennsylvania&rsquo;s above-average fees argue for the top of that range. Most Pennsylvania families land between $10,000 and $15,000, leaning toward $15,000."),
  ("Are final expense premiums higher in Pennsylvania?", "No &mdash; and that surprises people, because Pennsylvania&rsquo;s funeral bills are. Premiums are set by age, gender, tobacco use and health, so a 70-year-old in Pittsburgh pays the same as a 70-year-old in Phoenix for the same $10,000. What Pennsylvania changes is how much you buy: with the non-declinable basic services fee alone at $2,562, plan on the higher end of the coverage bands on this page."),
  ("Who regulates final expense insurance in Pennsylvania?", "The Pennsylvania Insurance Department, whose Consumer Help Center on its website takes questions and complaints about agents and insurers. Ask your agent for their Pennsylvania license number."),
 ],
)

COPY["ohio"] = dict(
 intro=P("A direct cremation in Ohio has a median cost of $1,850 and an immediate burial $2,648 &mdash; each within a few percent of the national medians. The funeral home is not the surprise on an Ohio funeral bill; the cemetery is, because it is left out of every published average. Final expense insurance covers both with a small whole life policy, usually $5,000 to $25,000, that pays cash directly to your family."),
 obs="<p><strong>Ohio tracks the national median</strong> &mdash; cremation 7% below, burial 5% below, the basic services fee 9% below &mdash; so the national averages are a fair guide to what an Ohio funeral home charges. What those averages leave out is the cemetery: a plot, vault, opening and closing and a marker add $2,000&ndash;$5,000 or more, and that is the line that turns a $2,648 burial into a $5,000 to $8,000 one.</p>",
 cov="<p>With Ohio&rsquo;s funeral-home charges at or a little below average, the coverage decision is mostly about the cemetery and the service. Cremation with a memorial gathering is well within $10,000; burial with a viewing in a Columbus, Cleveland or Cincinnati cemetery points toward $15,000.</p>",
 reg="<p>Final expense policies sold in Ohio are regulated by the <a href=\"https://insurance.ohio.gov/\" rel=\"noopener\">Ohio Department of Insurance</a>, whose Consumer Services line is 800-686-1526 (listed on the department&rsquo;s homepage) and which licenses the agents and carriers. Ask your agent for their Ohio license number.</p>",
 faq=[
  ("How much does a funeral cost in Ohio?", "From 31 Ohio funeral home price lists collected in 2026, the median direct cremation is $1,850 and the median immediate burial $2,648, both a few percent below the national medians of $1,995 and $2,800. Cemetery costs are separate and add $2,000&ndash;$5,000 or more."),
  ("Why does the total Ohio funeral bill end up so far above these figures?", "Because these are funeral-home charges only. In Ohio the funeral home is close to average, but the cemetery &mdash; plot, vault, opening and closing, marker &mdash; is a separate business with a separate bill. Adding it to Ohio&rsquo;s $2,648 burial median gives $4,648&ndash;$7,648 before any service."),
  ("How much final expense coverage does an Ohio family need?", "An immediate burial at $2,648 plus $2,000&ndash;$5,000 of cemetery costs is $4,648&ndash;$7,648. A full traditional funeral with a viewing and cemetery costs comes to $8,415&ndash;$11,415. With medical bills and small debts, most Ohio families land between $10,000 and $15,000."),
  ("Is $10,000 enough for an Ohio funeral?", "For cremation with a memorial gathering, comfortably: Ohio&rsquo;s $1,850 cremation median leaves most of a $10,000 policy for the gathering, medical bills and debts. For burial it depends on the cemetery; $2,648 at the funeral home plus a Columbus, Cleveland or Cincinnati plot, vault and marker can reach $7,648 before any service, which is why Ohio families choosing burial with a viewing tend toward $15,000."),
  ("Who regulates final expense insurance in Ohio?", "The Ohio Department of Insurance, which licenses agents and carriers and lists its Consumer Services line, 800-686-1526, on its homepage. Ask your agent for their Ohio license number."),
 ],
)

COPY["michigan"] = dict(
 intro=P("Michigan has the narrowest gap between cremation and burial of the eleven states we cover: a direct cremation runs $2,250 and an immediate burial $2,575, just 14% apart. Cremation saves a Michigan family far less at the funeral home than it saves a family in most other states. Final expense insurance covers either choice with a small whole life policy, usually $5,000 to $25,000, that pays cash directly to your family."),
 obs="<p><strong>In Michigan the cremation-versus-burial choice barely moves the funeral home&rsquo;s bill.</strong> Cremation at $2,250 is 13% above the national median while burial at $2,575 is 8% below it, which closes the gap between them to 14% &mdash; against 72% in North Carolina and about 40% nationally. Where cremation does still save a Michigan family money is the cemetery: skipping the plot, vault and marker removes $2,000&ndash;$5,000 or more.</p>",
 cov="<p>Because Michigan&rsquo;s funeral-home charges are similar either way, the coverage decision turns almost entirely on whether there will be a cemetery bill. Cremation with a memorial gathering is comfortably within $10,000; burial with a viewing points toward $15,000.</p>",
 reg="<p>Final expense policies sold in Michigan are regulated by the <a href=\"https://www.michigan.gov/difs\" rel=\"noopener\">Michigan Department of Insurance and Financial Services (DIFS)</a>, which licenses insurance agents and agencies alongside mortgage and consumer-finance businesses and explains on its site how to file a complaint with DIFS. Ask your agent for their Michigan license number.</p>",
 faq=[
  ("How much does a funeral cost in Michigan?", "From 29 Michigan funeral home price lists collected in 2026, the median direct cremation is $2,250 and the median immediate burial $2,575. Cremation is 13% above the national median of $1,995; burial is 8% below the national $2,800. Cemetery costs are separate and add $2,000&ndash;$5,000 or more."),
  ("Does cremation save much money in Michigan?", "At the funeral home, less than almost anywhere else: Michigan&rsquo;s $2,250 cremation and $2,575 burial medians are only 14% apart, the narrowest gap of the eleven states we cover. The real saving from cremation in Michigan is avoiding the cemetery bill &mdash; plot, vault, opening and closing, marker &mdash; not the funeral home&rsquo;s charge."),
  ("How much final expense coverage does a Michigan family need?", "An immediate burial at Michigan&rsquo;s $2,575 median plus $2,000&ndash;$5,000 of cemetery costs is $4,575&ndash;$7,575. A full traditional funeral with a viewing and cemetery costs comes to $8,415&ndash;$11,415. With medical bills and small debts, most Michigan families land between $10,000 and $15,000."),
  ("Are final expense rates different in Michigan?", "No. Rates are set by age, gender, tobacco use and health, not by state. In Michigan the useful question runs the other way: because cremation ($2,250) and burial ($2,575) cost nearly the same at the funeral home here, the coverage amount depends mostly on whether there will be a cemetery bill, not on which of the two you choose."),
  ("Who regulates final expense insurance in Michigan?", "The Michigan Department of Insurance and Financial Services (DIFS), which licenses agents and carriers and explains on its website how to file a complaint. Ask your agent for their Michigan license number."),
 ],
)

COPY["north-carolina"] = dict(
 intro=P("North Carolina has the widest gap between cremation and burial of the eleven states we cover: a direct cremation runs $1,700 and an immediate burial $2,920, a 72% difference. The choice between the two matters more here than anywhere else in the set. Final expense insurance covers either with a small whole life policy, usually $5,000 to $25,000, that pays cash directly to your family."),
 obs="<p><strong>In North Carolina, cremation versus burial is the decision.</strong> Cremation at $1,700 is 15% below the national median; burial at $2,920 is 4% above it, and the two are 72% apart before the cemetery is counted &mdash; against 14% in Michigan and about 40% nationally. Add the plot, vault and marker that burial requires and the same family&rsquo;s bill can differ by $4,000 or more depending on that one choice.</p>",
 cov="<p>A North Carolina family that has decided on cremation can size a policy at $10,000 with confidence. One that wants a burial should size toward $15,000, because the state&rsquo;s burial median is above national and the cemetery adds $2,000&ndash;$5,000 on top. If the decision is not made yet, insure for burial; the policy pays cash either way.</p>",
 reg="<p>Final expense policies sold in North Carolina are regulated by the <a href=\"https://www.ncdoi.gov/\" rel=\"noopener\">North Carolina Department of Insurance</a>, which licenses agents and carriers, takes complaints through the assistance section of its site and reports its recoveries from lost life insurance policies on its homepage &mdash; a reminder to tell your beneficiary where the policy is. Ask your agent for their North Carolina license number.</p>",
 faq=[
  ("How much does a funeral cost in North Carolina?", "From 13 North Carolina funeral home price lists collected in 2026, the median direct cremation is $1,700 and the median immediate burial $2,920. Cremation is 15% below the national median of $1,995; burial is 4% above the national $2,800. Cemetery costs are separate and add $2,000&ndash;$5,000 or more."),
  ("Why does cremation save so much in North Carolina?", "Because the two medians are unusually far apart: $1,700 against $2,920, a 72% gap and the widest of the eleven states we cover. Cremation also removes the cemetery&rsquo;s plot, vault and marker, so the total difference for a North Carolina family is routinely $4,000 or more."),
  ("How much final expense coverage does a North Carolina family need?", "An immediate burial at $2,920 plus $2,000&ndash;$5,000 of cemetery costs is $4,920&ndash;$7,920. A full traditional funeral with a viewing and cemetery costs comes to $8,415&ndash;$11,415. Cremation with a memorial is comfortably covered by $10,000; burial with a service points toward $15,000."),
  ("Are final expense rates different in North Carolina?", "No. Rates come from the same age, gender, tobacco and health tables in every state. In North Carolina the decision that moves the number is cremation versus burial &mdash; $1,700 against $2,920 before the cemetery &mdash; so two neighbors of the same age pay the same monthly premium for very different coverage needs."),
  ("How sure are these North Carolina figures?", "Less sure than for most states in our set: they come from 13 price lists, against 90 for California and 40 for Texas and Georgia. The 72% cremation-to-burial gap is large enough to survive a small sample, but treat the exact medians as a guide and ask the funeral home for its General Price List; the North Carolina Department of Insurance licenses the agent, not the funeral home, so the price list is your only check there."),
 ],
)

COPY["georgia"] = dict(
 intro=P("A direct cremation in Georgia has a median cost of $2,525 and an immediate burial $3,225 &mdash; 27% and 15% above the national medians, and the highest of the eleven states we cover. Final expense insurance covers those costs with a small whole life policy, usually $5,000 to $25,000, that pays cash directly to your family."),
 obs="<p><strong>Georgia is the most expensive of the eleven states we cover on both measures.</strong> Cremation at $2,525 is 27% above the national median, burial at $3,225 is 15% above, and the non-declinable basic services fee of $2,578 is 17% above. Forty price lists sit behind those figures, so this is not a small-sample quirk. A Georgia family sizing a policy on national averages will come up short.</p>",
 cov="<p>Georgia families should size toward the top of each band. Burial with cemetery costs already exceeds $8,000 at the upper end before any service; a full traditional funeral with a viewing points to $15,000, and even cremation with a gathering is more comfortably covered by $10,000 here than in a below-average state.</p>",
 reg="<p>Final expense policies sold in Georgia are regulated by the <a href=\"https://oci.georgia.gov/\" rel=\"noopener\">Georgia Office of Insurance and Safety Fire Commissioner</a>, whose Consumer Services Division describes itself as the office&rsquo;s investigative arm and takes complaints about insurers and agents through its website. Ask your agent for their Georgia license number.</p>",
 faq=[
  ("How much does a funeral cost in Georgia?", "From 40 Georgia funeral home price lists collected in 2026, the median direct cremation is $2,525 and the median immediate burial $3,225 &mdash; 27% and 15% above the national medians of $1,995 and $2,800, and the highest of the eleven states we cover. Cemetery costs are separate and add $2,000&ndash;$5,000 or more."),
  ("Are funerals really more expensive in Georgia than the national average?", "Yes, on every funeral-home charge we measured. The basic services fee, which cannot be declined, has a Georgia median of $2,578 against a national $2,195. With 40 price lists behind the figures, Georgia is one of the better-sampled states, so the finding is solid rather than a small-sample artifact."),
  ("How much final expense coverage does a Georgia family need?", "An immediate burial at Georgia&rsquo;s $3,225 median plus $2,000&ndash;$5,000 of cemetery costs is $5,225&ndash;$8,225 &mdash; the highest simplest-burial total of the eleven states we cover. A full traditional funeral with a viewing and cemetery costs comes to $8,415&ndash;$11,415 or more here. Most Georgia families should be looking at $15,000 rather than $10,000 for burial."),
  ("Are final expense premiums higher in Georgia?", "No. Premiums come from the same age, gender, tobacco and health tables everywhere. What Georgia changes is the coverage amount: with cremation at $2,525 and burial at $3,225, both well above national, the same $10,000 policy covers less of a Georgia funeral than it does elsewhere, which is why $15,000 is the more common recommendation here."),
  ("Who regulates final expense insurance in Georgia?", "The Georgia Office of Insurance and Safety Fire Commissioner, whose Consumer Services Division is the office&rsquo;s investigative arm and takes complaints about agents and insurers through its website. Ask your agent for their Georgia license number."),
 ],
)

COPY["arizona"] = dict(
 intro=P("A direct cremation in Arizona has a median cost of $1,240 and an immediate burial $2,045 &mdash; the second-lowest cremation cost in the country, 38% below the national median. Final expense insurance covers those costs with a small whole life policy, usually $5,000 to $25,000, that pays cash directly to your family."),
 obs="<p><strong>Arizona is the cheapest of the eleven states we cover, by a wide margin.</strong> Cremation at $1,240 is 38% below the national median and second-lowest in the country, behind only Nevada at $1,190; burial at $2,045 is 27% below national and the basic services fee of $1,550 is 29% below. Arizona had the second-largest net inflow of people 65 and over of any state in the 2022 Census survey, and a retiree arriving from a higher-cost state is often insuring against a bill that is smaller than they expect &mdash; at the funeral home. The cemetery still charges what it charges.</p>",
 cov="<p>Arizona&rsquo;s low funeral-home charges mean $10,000 covers more here than almost anywhere: cremation with a memorial gathering with room to spare, and even a simple burial with cemetery costs at the lower end of the range. A full traditional funeral with a viewing still points toward $10,000 to $15,000 once the cemetery is included.</p>",
 reg="<p>Final expense policies sold in Arizona are regulated by the <a href=\"https://difi.az.gov/\" rel=\"noopener\">Arizona Department of Insurance and Financial Institutions</a>, which oversees insurance producers alongside the state&rsquo;s banks and other financial institutions, publishes licensing information and takes complaints about both through its website. Ask your agent for their Arizona license number.</p>",
 faq=[
  ("How much does a funeral cost in Arizona?", "From 29 Arizona funeral home price lists collected in 2026, the median direct cremation is $1,240 &mdash; 38% below the national median of $1,995 and the second-lowest in the country &mdash; and the median immediate burial is $2,045, 27% below the national $2,800. Cemetery costs are separate and add $2,000&ndash;$5,000 or more."),
  ("Why is cremation so inexpensive in Arizona?", "The price lists show the result, not the reason: at $1,240, only Nevada ($1,190) is lower. Arizona&rsquo;s non-declinable basic services fee, $1,550 against a national $2,195, is a big part of it, since that fee is inside every cremation and burial price."),
  ("How much final expense coverage does an Arizona family need?", "An immediate burial at Arizona&rsquo;s $2,045 median plus $2,000&ndash;$5,000 of cemetery costs is $4,045&ndash;$7,045, the lowest simplest-burial total of the eleven states we cover. A full traditional funeral with a viewing and cemetery costs comes to $8,415&ndash;$11,415. Most Arizona families are well served between $10,000 and $15,000, and cremation is comfortably within $10,000."),
  ("I moved to Arizona in retirement. Should I adjust my coverage?", "Possibly downward at the funeral home, since Arizona&rsquo;s charges are 27 to 38% below national, but not before checking the cemetery and any medical bills or debts the policy should also cover. A licensed agent can rework the number with you."),
  ("Are final expense rates lower in Arizona?", "No. Rates are set by age, gender, tobacco use and health, not by state. What is lower in Arizona is the bill you are insuring against &mdash; a $1,240 cremation median against $1,995 nationally &mdash; which means a given policy amount goes further here than in Georgia or Pennsylvania."),
 ],
)
