# Medicare state-page copy. The county framing is deliberately identical on
# every page (availability is set by county, not state). The differentiation
# lives in the SHIP section and the regulator section, both written per state
# from verified sources:
#   SHIP names, sites and phones — shiphelp.org state listings
#     (https://www.shiphelp.org/ships/<state>/), read 12 Sep 2026; operating
#     agencies from the program sites those listings link to.
#   Regulator details — each department's homepage, fetched 12 Sep 2026
#     (services named here appear on that homepage).
# FMO standard throughout: no plan names, no named benefits, no premium
# figures, no $0 references, no superlatives.
P = lambda *ps: "\n".join(f"<p>{p}</p>" for p in ps)
COUNTY = "Medicare Advantage availability in {s} is set by county, not by state, so two people in the same state can have entirely different options."

def opener(state, ship_sentence):
    return P(COUNTY.format(s=state) + " " + ship_sentence,
             f"A licensed agent in our Greenwood Village, Colorado office compares the Medicare Advantage plans filed for your {state} county, explains the differences, and you decide. How <a href=\"/medicare/\">Medicare Advantage works</a> is the same in every state; what is available to you is not.")

COPY = {}

COPY["colorado"] = dict(
 intro=opener("Colorado", "Colorado&rsquo;s free, independent Medicare counseling comes from the State Health Insurance Assistance Program run by the Colorado Division of Insurance, the same office that licenses the agents who sell the plans."),
 counties=64,
 ship="<p>Colorado&rsquo;s program is the <a href=\"https://doi.colorado.gov/insurance-products/health-insurance/senior-health-care-medicare\" rel=\"noopener\">State Health Insurance Assistance Program (SHIP)</a>, run by the Colorado Division of Insurance and reachable at <a href=\"tel:+18886967213\">1-888-696-7213</a>, with a statewide Spanish-language counseling line at 303-894-5953. Like every SHIP it is federally funded and free: trained counselors who do not sell insurance help you compare plans, understand Medicare notices, apply for Extra Help with drug costs and appeal a denial. Because it sits inside the Division of Insurance, it is also the shortest path to the state&rsquo;s complaint process if a plan was sold to you badly. Program details as listed by <a href=\"https://www.shiphelp.org/ships/colorado/\" rel=\"noopener\">shiphelp.org</a>.</p>",
 reg="<p>The agents and agencies that sell Medicare Advantage in Colorado are licensed by the <a href=\"https://doi.colorado.gov/\" rel=\"noopener\">Colorado Division of Insurance</a>, part of the Department of Regulatory Agencies. Its site lets you verify an agent&rsquo;s license, file a complaint and check its status, and &mdash; unusually &mdash; run a &ldquo;Find Lost Life Insurance&rdquo; search for a deceased relative&rsquo;s policy. Senior Solutions Insurance is licensed there; our agents work from Greenwood Village, and you can look us up.</p>",
 faq=[
  ("Which Medicare Advantage plans are available in my part of Colorado?", "It depends on your county. Colorado has 64, and each plan files the counties it serves, so Denver County&rsquo;s list is not Larimer&rsquo;s, El Paso&rsquo;s or Mesa&rsquo;s on the Western Slope. A licensed agent compares the plans filed for your county; the Medicare Plan Finder at medicare.gov does the same by ZIP code."),
  ("Where can I get free, independent Medicare help in Colorado?", "From Colorado&rsquo;s State Health Insurance Assistance Program (SHIP), run by the Colorado Division of Insurance, at 1-888-696-7213, with Spanish-language counseling at 303-894-5953. It is federally funded, free, and staffed by counselors who do not sell insurance &mdash; a good second opinion on anything an agent tells you, including us."),
  ("Do I have to be in Colorado to work with Senior Solutions Insurance?", "No, but Colorado is where we are: our office is at 5775 DTC Blvd in Greenwood Village and our agents are licensed by the Colorado Division of Insurance first. If you live in the state, the person who calls you back is local, and you can verify their license on the Division&rsquo;s site."),
  ("How do I check that a Colorado Medicare agent is legitimate?", "Use the Colorado Division of Insurance&rsquo;s license verification, which is on its homepage, and ask for the agent&rsquo;s license number before the call ends. If a plan was sold to you in a way that felt wrong, the same site takes the complaint, and Colorado&rsquo;s SHIP at 1-888-696-7213 will tell you independently whether the plan fits."),
 ],
)

COPY["tennessee"] = dict(
 intro=opener("Tennessee", "Tennessee&rsquo;s free, independent Medicare counseling comes from its State Health Insurance Assistance Program, run by the Tennessee Department of Disability and Aging."),
 counties=95,
 ship="<p>Tennessee&rsquo;s program is the <a href=\"https://www.tn.gov/disability-and-aging/disability-aging-programs/tn-ship.html\" rel=\"noopener\">State Health Insurance Assistance Program (SHIP)</a>, run by the Tennessee Department of Disability and Aging and reachable at <a href=\"tel:+18778010044\">1-877-801-0044</a> (TTY 1-800-848-0299). It is federally funded and free: trained counselors who do not sell insurance help Tennesseans compare Medicare options, apply for Extra Help, and understand what a plan&rsquo;s paperwork means. Because it is housed with the state&rsquo;s aging and disability services rather than the insurance regulator, it is also a natural first call for anyone who is on Medicare because of a disability rather than age. Program details as listed by <a href=\"https://www.shiphelp.org/ships/tennessee/\" rel=\"noopener\">shiphelp.org</a>.</p>",
 reg="<p>The agents and agencies that sell Medicare Advantage in Tennessee are licensed by the Insurance Division of the <a href=\"https://www.tn.gov/commerce/insurance-division.html\" rel=\"noopener\">Tennessee Department of Commerce and Insurance</a>. Its site lets you verify an agent&rsquo;s license and file a complaint, and the same department houses the TennCare Oversight Division, which matters if you are dually eligible for Medicare and Tennessee&rsquo;s Medicaid program. Ask any agent for their Tennessee license number and check it there.</p>",
 faq=[
  ("Are the same Medicare Advantage plans available across Tennessee?", "No. Each plan files the counties it will serve, and Tennessee has 95 of them. Shelby County (Memphis), Davidson (Nashville), Knox and the rural counties of the Cumberland Plateau can each have a different list. A licensed agent compares the plans filed for your county specifically."),
  ("Where can Tennessee residents get free Medicare counseling?", "From Tennessee&rsquo;s State Health Insurance Assistance Program (SHIP), run by the Department of Disability and Aging, at 1-877-801-0044 or TTY 1-800-848-0299. It is federally funded and free, and its counselors do not sell insurance, which makes it a good independent check on any agent&rsquo;s advice."),
  ("I am on Medicare in Tennessee because of a disability, not age. Does that change anything?", "Not the plans that are filed for your county, but it can change your enrollment timing and whether you also qualify for TennCare. Tennessee&rsquo;s SHIP sits inside the Department of Disability and Aging and handles exactly these questions; the TennCare Oversight Division at the Department of Commerce and Insurance covers the Medicaid side."),
  ("Who do I complain to about a Medicare agent in Tennessee?", "The Insurance Division of the Tennessee Department of Commerce and Insurance licenses agents and takes complaints through its website, where you can also verify a license. For the plan itself, Medicare&rsquo;s own complaint process applies; Tennessee SHIP at 1-877-801-0044 can tell you which route fits your problem."),
 ],
)

COPY["florida"] = dict(
 intro=opener("Florida", "Florida&rsquo;s free Medicare counseling is SHINE &mdash; Serving Health Insurance Needs of Elders &mdash; run by the Department of Elder Affairs through the local Area Agencies on Aging."),
 counties=67,
 ship="<p>Florida&rsquo;s program is <a href=\"https://www.floridashine.org/\" rel=\"noopener\">SHINE &mdash; Serving Health Insurance Needs of Elders</a>, offered by the Florida Department of Elder Affairs and your local Area Agency on Aging, at <a href=\"tel:+18009635337\">1-800-963-5337</a> (TTY 1-800-955-8770). It is federally funded and free, and its counselors are trained volunteers who do not sell insurance; they help Medicare beneficiaries, families and caregivers compare plans, appeal denials and apply for Extra Help. In a state where 21.8% of residents are 65 or over &mdash; the fourth-highest share in the country in 2024 &mdash; SHINE is a good second opinion on anything an agent tells you. Program details as listed by <a href=\"https://www.shiphelp.org/ships/florida/\" rel=\"noopener\">shiphelp.org</a>.</p>",
 reg="<p>The agents and agencies that sell Medicare Advantage in Florida are licensed through the Florida Department of Financial Services, whose <a href=\"https://www.myfloridacfo.com/division/consumers\" rel=\"noopener\">Division of Consumer Services</a> runs the consumer helpline and takes complaints about how a plan was sold. The same department also regulates funeral homes and cemeteries through its Division of Funeral, Cemetery and Consumer Services, which is why Florida families dealing with both a Medicare question and a funeral bill often end up at one agency. Ask any agent for their Florida license number.</p>",
 faq=[
  ("Does Florida have more Medicare Advantage plans than other states?", "About 21.8% of Floridians are 65 or over, the fourth-highest share of any state in 2024, and many plans are filed here, but availability is still decided county by county across 67 counties. Miami-Dade&rsquo;s list is not Collier&rsquo;s, Polk&rsquo;s or the Panhandle&rsquo;s. A licensed agent compares exactly the plans filed for your county."),
  ("Where can Florida residents get free Medicare counseling?", "From SHINE &mdash; Serving Health Insurance Needs of Elders &mdash; Florida&rsquo;s State Health Insurance Assistance Program, run by the Department of Elder Affairs through the Area Agencies on Aging, at 1-800-963-5337 or TTY 1-800-955-8770. It is federally funded, free, and staffed by trained volunteers who do not sell insurance."),
  ("I split the year between Florida and another state. Which plans can I use?", "Medicare Advantage plans are tied to the county of your permanent residence, and many have service areas that do not follow you to a second home for routine care. Tell the agent how many months you are away, because it changes which plan types are worth comparing, and SHINE at 1-800-963-5337 can give you an independent view."),
  ("Who regulates Medicare agents in Florida?", "The Florida Department of Financial Services licenses them; its Division of Consumer Services runs the consumer helpline and takes complaints about how a plan was sold. Medicare itself approves and oversees the plans. If you are unsure whether a problem is with the agent or the plan, SHINE at 1-800-963-5337 will point you to the right door."),
 ],
)

COPY["texas"] = dict(
 intro=opener("Texas", "Texas&rsquo;s free Medicare counseling is HICAP &mdash; the Health Information, Counseling, and Advocacy Program &mdash; a partnership of Texas Health and Human Services, Texas Legal Services Center and the Area Agencies on Aging."),
 counties=254,
 ship="<p>Texas&rsquo;s program is the <a href=\"https://hhs.texas.gov/services/health/medicare\" rel=\"noopener\">Health Information, Counseling, and Advocacy Program (HICAP)</a>, a partnership between the Texas Health and Human Services Commission, Texas Legal Services Center and the Area Agencies on Aging, which trains and oversees certified benefits counselors across the state. The Texas Medicare Help Line is <a href=\"tel:+18002529240\">1-800-252-9240</a>. It is federally funded and free, and its counselors do not sell insurance; they help Texans compare plans, understand notices and appeal decisions. Do not confuse it with California&rsquo;s program of the same acronym &mdash; Texas HICAP is its own organization. Program details as listed by <a href=\"https://www.shiphelp.org/ships/texas/\" rel=\"noopener\">shiphelp.org</a>.</p>",
 reg="<p>The agents and agencies that sell Medicare Advantage in Texas are licensed by the <a href=\"https://www.tdi.texas.gov/\" rel=\"noopener\">Texas Department of Insurance</a>. Its site lets you look up a company or agent, file a complaint, and ask a question; Texas also has a separate Office of Public Insurance Counsel that represents consumers in insurance matters, linked from the department&rsquo;s homepage. Ask any agent for their Texas license number and look it up before you enroll.</p>",
 faq=[
  ("Why do my options differ from a relative&rsquo;s elsewhere in Texas?", "Because Medicare Advantage plans file by county, and Texas has 254 of them &mdash; more than any other state. A plan available in Dallas County may not be filed for Tarrant, and a plan in San Antonio may not exist in the Valley. A licensed agent compares only the plans filed for your county."),
  ("Where can Texans get free, independent Medicare help?", "From HICAP &mdash; the Health Information, Counseling, and Advocacy Program &mdash; Texas&rsquo;s State Health Insurance Assistance Program, run as a partnership of Texas Health and Human Services, Texas Legal Services Center and the Area Agencies on Aging. The Texas Medicare Help Line is 1-800-252-9240. It is federally funded and free, and the counselors do not sell insurance."),
  ("I live in a rural Texas county. Will I have any Medicare Advantage options?", "Possibly fewer than a metro county, and in some of Texas&rsquo;s 254 counties very few. That is exactly why the county-level check comes first; if the list for your county is short or empty, a licensed agent can tell you what the alternatives are, and HICAP&rsquo;s counselors will confirm it independently."),
  ("How do I check a Texas Medicare agent&rsquo;s license?", "On the Texas Department of Insurance website, which has an agent and company lookup on its homepage, along with the complaint form. Ask for the license number before the call ends. Texas also has an Office of Public Insurance Counsel that represents consumers in insurance matters if a dispute goes further."),
 ],
)

COPY["california"] = dict(
 intro=opener("California", "California&rsquo;s free Medicare counseling is the California Health Insurance Counseling and Advocacy Program (HICAP), run by the California Department of Aging."),
 counties=58,
 ship="<p>California&rsquo;s program is the <a href=\"https://www.aging.ca.gov/hicap/\" rel=\"noopener\">California Health Insurance Counseling and Advocacy Program (HICAP)</a>, run by the California Department of Aging, at <a href=\"tel:+18004340222\">1-800-434-0222</a> in California (1-800-677-1116 from outside the state). It is federally funded and free, and its registered counselors do not sell insurance; they help Californians compare plans, understand Medicare notices, appeal decisions and coordinate Medicare with Medi-Cal. California has more residents aged 65 and over than any other state &mdash; about 6.5 million in 2024, though only about 16.6% of the state&rsquo;s population &mdash; and HICAP counsels through local offices in every region. Program details as listed by <a href=\"https://www.shiphelp.org/ships/california/\" rel=\"noopener\">shiphelp.org</a>.</p>",
 reg="<p>The agents and agencies that sell Medicare Advantage in California are licensed by the <a href=\"https://www.insurance.ca.gov/\" rel=\"noopener\">California Department of Insurance</a>. Its site has a &ldquo;Check License Status&rdquo; tool and complaint forms, and the department publishes a consumer complaint study comparing insurers. Ask any agent for their California license number and check it before you enroll.</p>",
 faq=[
  ("Does living in a big California county mean more Medicare Advantage choices?", "Often, but it is the county that decides, not the state. Plans file for specific counties, so Los Angeles, San Diego and Sacramento each have their own list across California&rsquo;s 58 counties, and rural counties can have far shorter ones. A licensed agent compares the plans filed for your county."),
  ("Where can Californians get free Medicare counseling?", "From the California Health Insurance Counseling and Advocacy Program (HICAP), run by the California Department of Aging, at 1-800-434-0222. It is federally funded, free, and staffed by registered counselors who do not sell insurance and who also help coordinate Medicare with Medi-Cal."),
  ("I am moving between California counties. Does my plan come with me?", "Not necessarily. A plan is filed for specific counties, and moving to one it does not serve is a qualifying event that opens a Special Enrollment Period to choose again. Tell the agent your move date; HICAP&rsquo;s local office in your new county can confirm the timing independently."),
  ("How do I verify a California Medicare agent?", "Use &ldquo;Check License Status&rdquo; on the California Department of Insurance website and ask the agent for their license number. The same site takes complaints about how a plan was sold; HICAP at 1-800-434-0222 will tell you independently whether the plan itself fits."),
 ],
)

COPY["pennsylvania"] = dict(
 intro=opener("Pennsylvania", "Pennsylvania&rsquo;s free Medicare counseling is PA MEDI &mdash; Pennsylvania Medicare Education and Decision Insight &mdash; run by the Pennsylvania Department of Aging."),
 counties=67,
 ship="<p>Pennsylvania&rsquo;s program is <a href=\"https://www.pa.gov/agencies/aging/aging-programs-and-services/pa-medi-medicare-counseling\" rel=\"noopener\">PA MEDI &mdash; Pennsylvania Medicare Education and Decision Insight</a>, run by the Pennsylvania Department of Aging, at <a href=\"tel:+18007837067\">1-800-783-7067</a>. It is federally funded and free, and its counselors do not sell insurance; they help Pennsylvanians compare plans, understand what a plan&rsquo;s paperwork means and apply for Extra Help. The name is unusual &mdash; many states call their program SHIP &mdash; so if someone offers you &ldquo;free Medicare counseling&rdquo; in Pennsylvania under another name, check that it is PA MEDI or a licensed agent. Program details as listed by <a href=\"https://www.shiphelp.org/ships/pennsylvania/\" rel=\"noopener\">shiphelp.org</a>.</p>",
 reg="<p>The agents and agencies that sell Medicare Advantage in Pennsylvania are licensed by the <a href=\"https://www.pa.gov/agencies/insurance\" rel=\"noopener\">Pennsylvania Insurance Department</a>. Its Consumer Help Center lets you ask a question or file a complaint about how a plan was sold, and its consumer services portal tracks the answer. Ask any agent for their Pennsylvania license number before you enroll.</p>",
 faq=[
  ("Are Medicare Advantage options the same across Pennsylvania?", "No. Plans file for specific counties, and Pennsylvania has 67. Philadelphia, Allegheny (Pittsburgh), the Lehigh Valley and the rural center of the state each have their own list. A licensed agent compares the plans filed for your county."),
  ("Where can Pennsylvanians get free Medicare counseling?", "From PA MEDI &mdash; Pennsylvania Medicare Education and Decision Insight &mdash; the state&rsquo;s State Health Insurance Assistance Program, run by the Pennsylvania Department of Aging, at 1-800-783-7067. It is federally funded and free, and its counselors do not sell insurance."),
  ("I am moving within Pennsylvania. Can I change plans?", "If the move takes you to a county your current plan does not serve, that is a qualifying event and opens a Special Enrollment Period to choose a plan filed for the new county. Tell the agent your move date; PA MEDI at 1-800-783-7067 can confirm which window applies to you."),
  ("Who handles a complaint about a Medicare agent in Pennsylvania?", "The Pennsylvania Insurance Department, through the Consumer Help Center on its website, where you can ask a question or file a complaint about how a plan was sold. Medicare itself oversees the plans. PA MEDI will tell you which route fits and whether the plan you were sold is a reasonable fit."),
 ],
)

COPY["ohio"] = dict(
 intro=opener("Ohio", "Ohio&rsquo;s free Medicare counseling is OSHIIP &mdash; the Ohio Senior Health Insurance Information Program &mdash; run by the Ohio Department of Insurance, the same agency that licenses the agents."),
 counties=88,
 ship="<p>Ohio&rsquo;s program is the <a href=\"https://insurance.ohio.gov/consumers/medicare/01-oshiip\" rel=\"noopener\">Ohio Senior Health Insurance Information Program (OSHIIP)</a>, run by the Ohio Department of Insurance, at <a href=\"tel:+18006861578\">1-800-686-1578</a>. It is federally funded and free, and its counselors do not sell insurance; they help Ohioans compare plans, understand notices, apply for Extra Help and appeal denials. Because OSHIIP sits inside the insurance regulator, a problem with how a plan was sold and a question about the plan itself can be handled by the same department. Program details as listed by <a href=\"https://www.shiphelp.org/ships/ohio/\" rel=\"noopener\">shiphelp.org</a>.</p>",
 reg="<p>The agents and agencies that sell Medicare Advantage in Ohio are licensed by the <a href=\"https://insurance.ohio.gov/\" rel=\"noopener\">Ohio Department of Insurance</a>, whose Consumer Services line is 800-686-1526 (listed on the department&rsquo;s homepage). The same department runs OSHIIP, so Ohio is one of the few states where the Medicare counseling program and the agent regulator share a roof. Ask any agent for their Ohio license number.</p>",
 faq=[
  ("Do Cleveland, Columbus and Cincinnati have the same Medicare Advantage plans?", "No. Plans file for specific counties, and Ohio has 88 of them, so Cuyahoga, Franklin and Hamilton counties each have their own list, and a rural Appalachian county can have a very different one. A licensed agent compares only the plans filed for your county."),
  ("Where can Ohioans get free Medicare counseling?", "From the Ohio Senior Health Insurance Information Program (OSHIIP), run by the Ohio Department of Insurance, at 1-800-686-1578. It is federally funded and free, and OSHIIP counselors do not sell insurance."),
  ("I live in a rural Ohio county. Will I have Medicare Advantage options?", "Possibly fewer than a metro county. That is why the county-level check matters across Ohio&rsquo;s 88 counties: if the list for yours is short, a licensed agent can tell you what the alternatives are, and OSHIIP will confirm it independently."),
  ("Who do I call about a Medicare agent in Ohio?", "The Ohio Department of Insurance, whose Consumer Services line is 800-686-1526 and which licenses every agent selling Medicare Advantage in the state. Because OSHIIP is part of the same department, its counselors at 1-800-686-1578 can also tell you whether the plan you were sold fits."),
 ],
)

COPY["michigan"] = dict(
 intro=opener("Michigan", "Michigan&rsquo;s free Medicare counseling is the Michigan State Health Insurance Assistance Program, run through the Michigan Department of Health and Human Services."),
 counties=83,
 ship="<p>Michigan&rsquo;s program is the <a href=\"https://www.michigan.gov/mdhhs/adult-child-serv/adults-and-seniors/acls/state-health-insurance-assistance-program\" rel=\"noopener\">Michigan State Health Insurance Assistance Program (SHIP)</a>, run through the Michigan Department of Health and Human Services, at <a href=\"tel:+18008037174\">1-800-803-7174</a>. It is federally funded and free, and its counselors do not sell insurance; they help Michiganders compare plans, understand notices and coordinate Medicare with Michigan Medicaid. Because it is housed with the state&rsquo;s health and human services rather than the insurance regulator, it is a natural first call for anyone dually eligible. Program details as listed by <a href=\"https://www.shiphelp.org/ships/michigan/\" rel=\"noopener\">shiphelp.org</a>.</p>",
 reg="<p>The agents and agencies that sell Medicare Advantage in Michigan are licensed by the <a href=\"https://www.michigan.gov/difs\" rel=\"noopener\">Michigan Department of Insurance and Financial Services (DIFS)</a>, which also licenses mortgage and consumer-finance businesses. Its site explains how to file a complaint with DIFS about how a plan was sold. Ask any agent for their Michigan license number.</p>",
 faq=[
  ("Are the same Medicare Advantage plans available in the Upper Peninsula as in Detroit?", "Usually not. Plans file for specific counties, and Michigan has 83 of them. Wayne and Oakland counties, Kent County (Grand Rapids) and the Upper Peninsula each have their own list, and the U.P. counties can have far fewer options. A licensed agent compares the plans filed for your county."),
  ("Where can Michigan residents get free Medicare counseling?", "From the Michigan State Health Insurance Assistance Program (SHIP), run through the Michigan Department of Health and Human Services, at 1-800-803-7174. It is federally funded and free, and its counselors do not sell insurance and can also help coordinate Medicare with Michigan Medicaid."),
  ("I spend winters out of state. Does that affect my Michigan plan choice?", "It can. Medicare Advantage plans are tied to your county of permanent residence and many have service areas that do not extend to a second home for routine care. Tell the agent how long you are away each year; it changes which plan types are worth comparing, and Michigan SHIP at 1-800-803-7174 can give you an independent view."),
  ("Who regulates Medicare agents in Michigan?", "The Michigan Department of Insurance and Financial Services (DIFS) licenses them and explains on its website how to file a complaint about how a plan was sold. Medicare itself approves and oversees the plans. For a question about whether the plan fits, Michigan SHIP is the free, independent route."),
 ],
)

COPY["north-carolina"] = dict(
 intro=opener("North Carolina", "North Carolina&rsquo;s free Medicare counseling is SHIIP &mdash; the Seniors&rsquo; Health Insurance Information Program &mdash; run by the North Carolina Department of Insurance, which also licenses the agents."),
 counties=100,
 ship="<p>North Carolina&rsquo;s program is the <a href=\"https://www.ncdoi.gov/consumers/medicare-and-seniors-health-insurance-information-program-shiip\" rel=\"noopener\">Seniors&rsquo; Health Insurance Information Program (SHIIP)</a>, run by the North Carolina Department of Insurance, at <a href=\"tel:+18554081212\">1-855-408-1212</a>. It is federally funded and free, and its counselors do not sell insurance; they help North Carolinians compare plans, understand notices, apply for Extra Help and appeal denials. Note the spelling &mdash; SHIIP with two i&rsquo;s &mdash; which is North Carolina&rsquo;s own; the national program is SHIP. Program details as listed by <a href=\"https://www.shiphelp.org/ships/north-carolina/\" rel=\"noopener\">shiphelp.org</a>.</p>",
 reg="<p>The agents and agencies that sell Medicare Advantage in North Carolina are licensed by the <a href=\"https://www.ncdoi.gov/\" rel=\"noopener\">North Carolina Department of Insurance</a>, which runs both SHIIP and Smart NC, its health-insurance consumer assistance program, and offers help on its homepage for anyone whose health insurance claim was denied. Ask any agent for their North Carolina license number.</p>",
 faq=[
  ("Are Charlotte and Raleigh Medicare Advantage options the same as the mountains or the coast?", "No. Plans file for specific counties, and North Carolina has 100 of them. Mecklenburg, Wake, the western mountain counties and the eastern coastal counties each have their own list. A licensed agent compares the plans filed for your county."),
  ("Where can North Carolinians get free Medicare counseling?", "From the Seniors&rsquo; Health Insurance Information Program (SHIIP), run by the North Carolina Department of Insurance, at 1-855-408-1212. It is federally funded and free, and SHIIP counselors do not sell insurance."),
  ("I retired to North Carolina from another state. Can I change my plan?", "Moving to a new county is a qualifying event that opens a Special Enrollment Period, because the plans available to you have changed. Tell the agent your move date; the window is limited, and SHIIP at 1-855-408-1212 will confirm your timing for free."),
  ("Who handles a complaint about a Medicare agent in North Carolina?", "The North Carolina Department of Insurance, which licenses the agents, takes complaints through the assistance section of its website and also runs SHIIP and Smart NC. If your problem is a denied health insurance claim rather than how a plan was sold, the department&rsquo;s homepage has a dedicated route for that too."),
 ],
)

COPY["georgia"] = dict(
 intro=opener("Georgia", "Georgia&rsquo;s free Medicare counseling is the Georgia State Health Insurance Assistance Program, run through the Division of Aging Services."),
 counties=159,
 ship="<p>Georgia&rsquo;s program is the <a href=\"https://aging.georgia.gov/georgia-ship\" rel=\"noopener\">Georgia State Health Insurance Assistance Program</a>, run through the Georgia Division of Aging Services, at <a href=\"tel:+18665524464\">1-866-552-4464</a>. It is federally funded and free, and its counselors do not sell insurance; they help Georgians compare plans, understand Medicare notices and apply for Extra Help. shiphelp.org lists the program under its full name rather than an acronym, so if you see it referred to by another name, confirm it is the Division of Aging Services program before you rely on it. Program details as listed by <a href=\"https://www.shiphelp.org/ships/georgia/\" rel=\"noopener\">shiphelp.org</a>.</p>",
 reg="<p>The agents and agencies that sell Medicare Advantage in Georgia are licensed by the <a href=\"https://oci.georgia.gov/\" rel=\"noopener\">Georgia Office of Insurance and Safety Fire Commissioner</a>, whose Consumer Services Division is, in its own words, the investigative arm of the office and takes complaints about insurance providers and agents through its website. Ask any agent for their Georgia license number.</p>",
 faq=[
  ("Why does Georgia&rsquo;s county count matter for Medicare Advantage?", "Because plans file by county and Georgia has 159 of them, more than any state except Texas. Fulton, DeKalb and the other metro Atlanta counties can each have a different list, and rural south Georgia counties often have much shorter ones. A licensed agent compares only the plans filed for your county."),
  ("Where can Georgians get free Medicare counseling?", "From the Georgia State Health Insurance Assistance Program, run through the Georgia Division of Aging Services, at 1-866-552-4464. It is federally funded and free, and its counselors do not sell insurance."),
  ("I live in a rural Georgia county. Will I have options?", "Possibly fewer than metro Atlanta, and in some of Georgia&rsquo;s 159 counties very few. That is exactly why the county check comes first: if the list is short, a licensed agent can tell you what alternatives exist, and the Georgia SHIP counselors will confirm it independently."),
  ("Who investigates a complaint about a Medicare agent in Georgia?", "The Consumer Services Division of the Georgia Office of Insurance and Safety Fire Commissioner, which describes itself as the office&rsquo;s investigative arm and takes complaints about agents and insurers through its website. Medicare oversees the plans themselves; Georgia&rsquo;s SHIP at 1-866-552-4464 can tell you which route fits."),
 ],
)

COPY["arizona"] = dict(
 intro=opener("Arizona", "Arizona&rsquo;s free Medicare counseling is the Arizona State Health Insurance Assistance Program, delivered through the state&rsquo;s Area Agencies on Aging."),
 counties=15,
 ship="<p>Arizona&rsquo;s program is the <a href=\"https://azship.org/\" rel=\"noopener\">Arizona State Health Insurance Assistance Program (SHIP)</a>, delivered through the state&rsquo;s Area Agencies on Aging, at <a href=\"tel:+18004324040\">1-800-432-4040</a>. It is federally funded and free, and its counselors do not sell insurance; the program describes its work as local, in-depth and objective counseling for Medicare-eligible people, their families and caregivers. For the many people who move to Arizona in retirement, it is also the independent place to ask how a move changes your enrollment rights. Program details as listed by <a href=\"https://www.shiphelp.org/ships/arizona/\" rel=\"noopener\">shiphelp.org</a>.</p>",
 reg="<p>The agents and agencies that sell Medicare Advantage in Arizona are licensed by the <a href=\"https://difi.az.gov/\" rel=\"noopener\">Arizona Department of Insurance and Financial Institutions</a>, which also oversees banks and other financial institutions in the state. Its site publishes licensing information and takes complaints about insurance entities and producers. Ask any agent for their Arizona license number.</p>",
 faq=[
  ("With only 15 counties, are Arizona Medicare Advantage options the same everywhere?", "No. Fifteen counties is fewer lists than many states, but they are still separate lists. Maricopa, Pima and Yavapai counties each have plans filed specifically for them, and the rural counties can have far fewer. A licensed agent compares the plans filed for your county."),
  ("Where can Arizonans get free Medicare counseling?", "From the Arizona State Health Insurance Assistance Program (SHIP), delivered through the Area Agencies on Aging, at azship.org or 1-800-432-4040. It is federally funded and free, and its counselors do not sell insurance."),
  ("I just moved to Arizona. Can I change my Medicare Advantage plan?", "Yes. Moving to a new county is a qualifying event that opens a Special Enrollment Period, because the plans available to you have changed. Many Arizona retirees are in exactly this position; tell the agent your move date, since the window is limited, and Arizona SHIP will confirm your rights independently."),
  ("Who regulates Medicare agents in Arizona?", "The Arizona Department of Insurance and Financial Institutions, which licenses insurance producers alongside the state&rsquo;s financial institutions and takes complaints about both through its website. Medicare oversees the plans; Arizona SHIP at 1-800-432-4040 is the free, independent route for a question about whether a plan fits."),
 ],
)
